# 수면 데이터 불러오기 및 기본 구조 탐색

In [34]:
import pandas as pd

In [35]:
#csv 데이터 읽기

df = pd.read_csv(
    "Sleep_health_and_lifestyle_dataset.csv",
)

In [36]:
#데이터넷 구조보기

df.shape

(374, 13)

In [37]:
#Feauture의 데이터 타입 보기

df.dtypes

Person ID                    int64
Gender                         str
Age                          int64
Occupation                     str
Sleep Duration             float64
Quality of Sleep             int64
Physical Activity Level      int64
Stress Level                 int64
BMI Category                   str
Blood Pressure                 str
Heart Rate                   int64
Daily Steps                  int64
Sleep Disorder                 str
dtype: object

In [38]:
#고객ID int -> str 데이터 타입 바꾸기

df["Person ID"] = df["Person ID"].astype(str)

In [39]:
df.dtypes

Person ID                      str
Gender                         str
Age                          int64
Occupation                     str
Sleep Duration             float64
Quality of Sleep             int64
Physical Activity Level      int64
Stress Level                 int64
BMI Category                   str
Blood Pressure                 str
Heart Rate                   int64
Daily Steps                  int64
Sleep Disorder                 str
dtype: object

In [40]:
# Person ID	개인 식별 번호
# Gender	성별
# Age	나이
# Occupation	직업
# Sleep Duration	수면 시간
# Quality of Sleep	수면의 질 점수
# Physical Activity Level	신체 활동 수준
# Stress Level	스트레스 수준
# BMI Category	체질량지수(BMI) 범주
# Blood Pressure	혈압
# Heart Rate	심박수
# Daily Steps	하루 걸음 수
# Sleep Disorder	수면장애 유형

In [41]:
#데이터 샘플 보기(맨 앞 10개)

df.head(10)

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
5,6,Male,28,Software Engineer,5.9,4,30,8,Obese,140/90,85,3000,Insomnia
6,7,Male,29,Teacher,6.3,6,40,7,Obese,140/90,82,3500,Insomnia
7,8,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,NaN
8,9,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,NaN
9,10,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,NaN

In [42]:
#데이터 샘플 보기(맨 뒤 10개)

df.tail(10)

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
364,365,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
365,366,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
366,367,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
367,368,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
368,369,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
369,370,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
370,371,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
371,372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
372,373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
373,374,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea

In [43]:
#결측치 개수 확인

df.isna().sum()

Person ID                    0
Gender                       0
Age                          0
Occupation                   0
Sleep Duration               0
Quality of Sleep             0
Physical Activity Level      0
Stress Level                 0
BMI Category                 0
Blood Pressure               0
Heart Rate                   0
Daily Steps                  0
Sleep Disorder             219
dtype: int64

In [44]:
#한 컬럼에 어떤 값들이 있는지 확인

print(f"수면장애 유형: \n{df["Sleep Disorder"].unique()}\n")

print(f"직업: \n{df["Occupation"].unique()}")

수면장애 유형:
<StringArray>
[nan, 'Sleep Apnea', 'Insomnia']
Length: 3, dtype: str

직업:
<StringArray>
[   'Software Engineer',               'Doctor', 'Sales Representative',
              'Teacher',                'Nurse',             'Engineer',
           'Accountant',            'Scientist',               'Lawyer',
          'Salesperson',              'Manager']
Length: 11, dtype: str

In [45]:
#csv의 수면장애 유형 : "None"은 결측치가 아닌 수면장애가 없다는 뜻 그래서 "None" 이 결측치로 입력되지 않게 해야 함

df = pd.read_csv(
    "Sleep_health_and_lifestyle_dataset.csv",
    keep_default_na=False
)

In [46]:
df.isna().sum()

Person ID                  0
Gender                     0
Age                        0
Occupation                 0
Sleep Duration             0
Quality of Sleep           0
Physical Activity Level    0
Stress Level               0
BMI Category               0
Blood Pressure             0
Heart Rate                 0
Daily Steps                0
Sleep Disorder             0
dtype: int64

In [47]:
df["Sleep Disorder"].unique()

<StringArray>
['None', 'Sleep Apnea', 'Insomnia']
Length: 3, dtype: str

# 조건 필터링

In [48]:
#수면 시간이 6시간 이상인 행 데이터 뽑기

df[df["Quality of Sleep"] >= 6]

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,None
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
6,7,Male,29,Teacher,6.3,6,40,7,Obese,140/90,82,3500,Insomnia
7,8,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,370,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
370,371,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
371,372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
372,373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
373,374,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea

In [49]:
#직업이 의사인 행 데이터 뽑기

df[df["Occupation"] == "Doctor"]

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
7,8,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,None
8,9,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,None
9,10,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
266,267,Male,48,Doctor,7.3,7,65,5,Obese,142/92,83,3500,Insomnia
276,277,Male,49,Doctor,8.1,9,85,3,Obese,139/91,86,3700,Sleep Apnea
277,278,Male,49,Doctor,8.1,9,85,3,Obese,139/91,86,3700,Sleep Apnea
341,342,Female,56,Doctor,8.2,9,90,3,Normal Weight,118/75,65,10000,None
342,343,Female,56,Doctor,8.2,9,90,3,Normal Weight,118/75,65,10000,None

In [50]:
# 성별이 남자이면서 스트레스 레벨이 5 이상인 사람

df[(df["Gender"] == "Male") & (df["Stress Level"] >= 5)]

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,None
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,248,Male,44,Engineer,6.8,7,45,7,Overweight,130/85,78,5000,Insomnia
248,249,Male,44,Salesperson,6.4,6,45,7,Overweight,130/85,72,6000,None
249,250,Male,44,Salesperson,6.5,6,45,7,Overweight,130/85,72,6000,None
264,265,Male,48,Doctor,7.3,7,65,5,Obese,142/92,83,3500,Insomnia
266,267,Male,48,Doctor,7.3,7,65,5,Obese,142/92,83,3500,Insomnia

In [51]:
#직업이 의사거나 간호사인 사람중에서 수면시간이 7시간 미만인 사람
#isin(): 컬럼안에 ()안에 있는 값이 있으면 True

df[(df["Occupation"].isin(["Doctor", "Nurse"])) & (df["Sleep Duration"] < 7)]

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
10,11,Male,29,Doctor,6.1,6,30,8,Normal,120/80,70,8000,None
12,13,Male,29,Doctor,6.1,6,30,8,Normal,120/80,70,8000,None
13,14,Male,29,Doctor,6.0,6,30,8,Normal,120/80,70,8000,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,297,Female,50,Nurse,6.1,6,90,8,Overweight,140/95,75,10000,Sleep Apnea
297,298,Female,50,Nurse,6.1,6,90,8,Overweight,140/95,75,10000,Sleep Apnea
303,304,Female,51,Nurse,6.0,6,90,8,Overweight,140/95,75,10000,Sleep Apnea
304,305,Female,51,Nurse,6.1,6,90,8,Overweight,140/95,75,10000,Sleep Apnea
305,306,Female,51,Nurse,6.1,6,90,8,Overweight,140/95,75,10000,Sleep Apnea

In [52]:
#나이가 40이상 50이하인 사람
#between(a,b) : a이상 b이하

df[df["Age"].between(40,50)]

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
161,162,Female,40,Accountant,7.2,8,55,6,Normal Weight,119/77,73,7300,None
162,163,Female,40,Accountant,7.2,8,55,6,Normal Weight,119/77,73,7300,None
163,164,Male,40,Lawyer,7.9,8,90,5,Normal,130/85,68,8000,None
164,165,Male,40,Lawyer,7.9,8,90,5,Normal,130/85,68,8000,None
165,166,Male,41,Lawyer,7.6,8,90,5,Normal,130/85,70,8000,Insomnia
...,...,...,...,...,...,...,...,...,...,...,...,...,...
293,294,Female,50,Nurse,6.0,6,90,8,Overweight,140/95,75,10000,Sleep Apnea
294,295,Female,50,Nurse,6.1,6,90,8,Overweight,140/95,75,10000,Sleep Apnea
295,296,Female,50,Nurse,6.0,6,90,8,Overweight,140/95,75,10000,Sleep Apnea
296,297,Female,50,Nurse,6.1,6,90,8,Overweight,140/95,75,10000,Sleep Apnea
297,298,Female,50,Nurse,6.1,6,90,8,Overweight,140/95,75,10000,Sleep Apnea